# Generated by Django 6.0.1 on 2026-04-01 18:41

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6,8}$', 'Registration Number must contain between 6 to 8 uppercase alphanumeric characters')])),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.URLField(blank=True, null=True, validators=[common.validators.PhotoURLValidate('URL must point to a valid image file (.jpg, .jpeg, .png, .gif, .webp)')])),
                ('vehicle_type', models.CharField(choices=[('Truck', 'Truck'), ('Van', 'Van'), ('Car', 'Car')], max_length=10)),
                ('capacity_kg', models.PositiveIntegerField()),
                ('manufacture_date', models.DateField()),
            ],
        ),
    ]
